### ISSUE TITLE
Python3.6, ok; Python3.8, error

### ISSUE THREAD

**Issue by Williamlizl** [zihangJiang/TokenLabeling#15]
`Test: [   0/1]  Time: 11.293 (11.293)  Loss:  0.7043 (0.7043)  Acc@1: 42.1875 (42.1875)  Acc@5: 100.0000 (100.0000)
Test: [   1/1]  Time: 0.108 (5.701)  Loss:  0.5847 (0.6689)  Acc@1: 89.8148 (56.3187)  Acc@5: 100.0000 (100.0000)
free(): invalid pointer
free(): invalid pointer
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 303, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 294, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3.8', '-u', 'main.py', '--local_rank=1', './dataset/c/c', '--model', 'lvvit_s', '-b', '128', '--apex-amp', '--img-size', '224', '--drop-path', '0.1', '--token-label', '--token-label-size', '14', '--dense-weight', '0.0', '--num-classes', '2', '--finetune', './pretrained/lvvit_s-26M-384-84-4.pth.tar']' died with <Signals.SIGABRT: 6>.
root@btq3ajqsfk1cu-0:/puxin_libochao/TokenLabeling# CUDA_VISIBLE_DEVICES=0,1 bash ./distributed_train.sh 2 ./dataset/c/c --model lvvit_s -b 128 --apex-amp --img-size 224 --drop-path 0.1 --token-label --token-label-size 14 --dense-weight 0.0 --num-classes 2 --finetune ./pretrained/lvvit_s-26M-384-84-4.pth.tar`

**Comment by zihangJiang** [comment]
Hi @Williamlizl, thanks for reporting the issue. I'm not sure if this error is related to the RAM, but it seems that the error is not caused by our code. You may try to use a smaller batch size or switch to python3.6.
